version: "2"
services:
  nginx:
    restart: always
    image: "nginx:mainline-alpine"
    ports:
      - 8000:80
    volumes:
      - "./nginx/conf:/etc/nginx/"
      - "./htdocs:/var/www/html"
    depends_on:
      - phpfpm
    links:
      - phpfpm
  phpfpm:
    restart: always
    build: ./phpfpm/
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./htdocs:/var/www/html"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./shared/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./shared/mysql/db:/var/lib/mysql
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "4444:80"
    environment:
     - PMA_ARBITRARY=1
     - MYSQL_USERNAME=user
     - MYSQL_PASSWORD=password
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:db
    container_name: phpmyadmin
